### ISSUE TITLE
Error while try to deploy example from wiki with custompodautoscaler.com/v1alpha1

### ISSUE THREAD

**Issue by MynameisFragile** [jthomperoo/horizontal-pod-autoscaler#33]
I tried to use ur  custom autoscaler , but was not able to run example from wiki in my cluster 

the error message is " no matches for kind "CustomPodAutoscaler" in version "custompodautoscaler.com/v1alpha1"
ensure CRDs are installed first" 

example file was found here 
https://horizontal-pod-autoscaler.readthedocs.io/en/latest/reference/configuration/

Is this example still actual? 

P.S.
custom-pod-autoscaler-operator was installed with manifest file , cluster wide, VERSION=v1.3.0

**Comment by jthomperoo** [comment]
Ah, that example has a mistake, good spot, it should be using `custompodautoscaler.com/v1` instead of `custompodautoscaler.com/v1alpha1` - I'll get that updated.

**Comment by MynameisFragile** [comment]
Thank you a lot sir !)
